os:
  editCommand: 'nvr'
  editCommandTemplate: "{{editor}} -l {{filename}} +{{line}}"
gui:
  showIcons: true
customCommands:
  - key: 'G'
    command: 'gitmoji -c'
    context: 'files'
    subprocess: yes
    description: 'Commit with gitmoji'
    stream: yes
    showOutput: yes
