abbr npmg "npm i -g "
abbr npmS "npm i -S "
abbr npmD "npm i -D "
abbr npmF 'npm i -f'
abbr npmE 'PATH="$(npm bin)":"$PATH"'
abbr npmO "npm outdated"
abbr npmU "npm update"
abbr npmV "npm -v"
abbr npmL "npm list"
abbr npmL0 "npm ls --depth=0"
abbr npmst "npm start"
abbr npmt "npm test"
abbr npmR "npm run"
abbr npmP "npm publish"
abbr npmI "npm init"
abbr npmi "npm info"
abbr npmSe "npm search"
abbr npmrd "npm run dev"
abbr npmrb "npm run build"
